plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
    id 'org.spongepowered.mixin' version "${mixin_gradle_version}"
    id 'wtf.gofancy.fancygradle' version "${fancy_gradle_version}"
}

// Temporary indev runs naming for FermiumBooter spaces in jar name
def isIndevRun = gradle.startParameter.taskNames.any { it.startsWith('runClient') || it.startsWith('runServer') }

version = mod_version
group = mod_id
base.archivesName = isIndevRun ? mod_id : mod_name

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: mappings_channel, version: mappings_version

    runs {
        server {
            jvmArg "-Dfml.coreMods.load=betterconfig.asm.BetterConfigPlugin,${mixin_loader_class}"
//            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"
            jvmArg "-Dmixin.debug.export=true"

            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }

        client {
            parent minecraft.runs.server

            args "--username=InDev"
        }

        clientAllMods {
            parent minecraft.runs.client

            workingDirectory project.file('runPack')
        }

        serverAllMods {
            parent minecraft.runs.server

            workingDirectory project.file('runPack')
        }
    }
}

repositories {
    flatDir { dirs 'libs' }
    maven { url = 'https://www.cursemaven.com' }
}

def runOptionalMods = gradle.startParameter.taskNames.any { it.startsWith('run') && it.endsWith('AllMods')}
def optionalRuntime = [
        "curse.maven:jei-${jei_version}",
]
def optionalImplementation = [
        "curse.maven:bloodmoon-${bloodmoon_version}",
        "curse.maven:champions-${champions_version}",
        "curse.maven:defiled-lands-${defiledlands_version}",
        "curse.maven:first-aid-${firstaid_version}",
        "curse.maven:atomicstrykers-infernal-mobs-${infernalmobs_version}",
        "curse.maven:lycanitesmobs-${lycanitesmobs_version}",
        "curse.maven:rlmixins-${rlmixins_version}",
        "curse.maven:scape-and-run-parasites-${srparasites_version}"
]

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    compileOnly "org.spongepowered:mixin:${mixin_version}"
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    compileOnly "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"

    implementation fg.deobf("curse.maven:fermiumbooter-${fermiumbooter_version}")
    implementation fg.deobf('io.github.meldexun:betterconfig:1.12.2-1.3.0')

    implementation fg.deobf("curse.maven:silentlib-${silentlib_version}")
    implementation fg.deobf("curse.maven:scalinghealth-${scalinghealth_version}")

    optionalRuntime.each { dep ->
        if (runOptionalMods) runtimeOnly fg.deobf(dep)
    }
    optionalImplementation.each { dep ->
        if (runOptionalMods) implementation fg.deobf(dep)
        else compileOnly fg.deobf(dep)
    }
}

mixin {
    add sourceSets.main, "mixins.${mod_id}.refmap.json"
}

fancyGradle {
    patches {
        resources
        coremods
        asm
        mergetool
    }
}

// For indev run
def mcpMappingsDir = file('mcp')

tasks.register('prepareMinecraftMappings', Copy) {
    dependsOn 'extractMappings'
    from(layout.buildDirectory.dir('extractMappings')) {
        include 'fields.csv'
        include 'methods.csv'
    }
    into(mcpMappingsDir)
}

tasks.configureEach {
    if (name.startsWith('prepareRun')) {
        dependsOn 'prepareMinecraftMappings'
    }
}

processResources {
    var replaceProperties = [
            'mod_id': mod_id,
            'mod_name': mod_name,
            'version': mod_version,
            'mcversion': minecraft_version,
            'mod_description': mod_description,
            'mod_author': mod_author
    ]

    inputs.properties replaceProperties

    filesMatching('mcmod.info') {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : mod_name,
                "Specification-Version"   : "1",
                "Specification-Vendor"   : mod_author,
                "Implementation-Title"    : mod_name,
                "Implementation-Version"  : mod_version,
                "Implementation-Vendor"   : mod_author,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "FMLCorePlugin": mixin_loader_class,
                "FMLCorePluginContainsFMLMod": "true",
        ])
    }
}

tasks.named('compileJava') {
    options.incremental = false
}

jar.finalizedBy('reobfJar')