plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
    id 'org.spongepowered.mixin' version "${mixin_gradle_version}"
    id 'wtf.gofancy.fancygradle' version "${fancy_gradle_version}"
}

version = mod_version
group = mod_id
base.archivesName = mod_name

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: mappings_channel, version: mappings_version

    runs {
        server {
            jvmArg "-Dfml.coreMods.load=${mixin_loader_class}"
//            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"
            jvmArg "-Dmixin.debug.export=true"

            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }

        client {
            parent minecraft.runs.server

            args "--username=InDev"
        }

        clientAllMods {
            parent minecraft.runs.client

            workingDirectory project.file('runPack')
        }

        serverAllMods {
            parent minecraft.runs.server

            workingDirectory project.file('runPack')
        }
    }
}

repositories {
    flatDir { dirs 'libs' }
    maven { url = 'https://www.cursemaven.com' }
}

def runOptionalMods = gradle.startParameter.taskNames.any { it.startsWith('run') && it.endsWith('AllMods')}
def optionalRuntime = [
        "curse.maven:jei-${jei_version}",
]
def optionalImplementation = [
        "curse.maven:bloodmoon-${bloodmoon_version}",
        "curse.maven:champions-${champions_version}",
        "curse.maven:first-aid-${firstaid_version}",
        "curse.maven:atomicstrykers-infernal-mobs-${infernalmobs_version}",
        "curse.maven:lycanitesmobs-${lycanitesmobs_version}",
        "curse.maven:rlmixins-${rlmixins_version}"
]

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    compileOnly "org.spongepowered:mixin:${mixin_version}"
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    compileOnly "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"

    implementation fg.deobf("curse.maven:fermiumbooter-${fermiumbooter_version}")

    implementation fg.deobf("curse.maven:silentlib-${silentlib_version}")
    implementation fg.deobf("curse.maven:scalinghealth-${scalinghealth_version}")

    optionalRuntime.each { dep ->
        if (runOptionalMods) runtimeOnly fg.deobf(dep)
    }
    optionalImplementation.each { dep ->
        if (runOptionalMods) implementation fg.deobf(dep)
        else compileOnly fg.deobf(dep)
    }
}

mixin {
    add sourceSets.main, "mixins.${mod_id}.refmap.json"
}

fancyGradle {
    patches {
        resources
        coremods
        asm
        mergetool
    }
}

// For indev run
def mcpMappingsDir = file('mcp')

tasks.register('prepareMinecraftMappings', Copy) {
    dependsOn 'extractMappings'
    from(layout.buildDirectory.dir('extractMappings')) {
        include 'fields.csv'
        include 'methods.csv'
    }
    into(mcpMappingsDir)
}

tasks.configureEach {
    if (name.startsWith('prepareRun')) {
        dependsOn 'prepareMinecraftMappings'
    }
}

processResources {
    var replaceProperties = [
            'mod_id': mod_id,
            'mod_name': mod_name,
            'version': mod_version,
            'mcversion': minecraft_version,
            'mod_description': mod_description,
            'mod_author': mod_author
    ]

    inputs.properties replaceProperties

    filesMatching('mcmod.info') {
        expand replaceProperties
    }
}

jar {
    manifest {
        def attr = [:]
        attr['Specification-Title']         = mod_name
        attr['Specification-Vendor']        = mod_author
        attr['Specification-Version']       = '1'
        attr['Implementation-Title']        = mod_name
        attr['Implementation-Vendor']       = mod_author
        attr['Implementation-Version']      = mod_version
        attr['Implementation-Timestamp']    = new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        attr['FMLCorePlugin']               = mixin_loader_class
        attr['FMLCorePluginContainsFMLMod'] = 'true'
        attr['TweakClass']                  = 'org.spongepowered.asm.launch.MixinTweaker'
        attr['ForceLoadAsMod'] = gradle.startParameter.taskNames.any { !it.startsWith('runClient') && !it.startsWith('runServer')}
        attributes(attr)
    }
}

jar.finalizedBy('reobfJar')