# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12
fancy_gradle_version=1.1.+

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7
mixin_extras_version=0.5.0

# mod
mod_id=scalinghealthissues
mod_name=Scaling Health Issues
mod_version=0.0.0
mod_author=["cdstk"]
mod_description=Various changes to the Scaling Health mod for 1.12
mixin_loader_class=scalinghealthissues.ScalingHealthIssuesPlugin

# dependencies
fermiumbooter_version=968474:6848644
silentlib_version=242998:2851111
scalinghealth_version=248027:2816920
jei_version=238222:5846804

bloodmoon_version=226321:2537917
champions_version=307152:3177947
infernalmobs_version=227875:3431758
lycanitesmobs_version=224770:5750564
rlmixins_version=711730:8151138